apiVersion: v1
description:  ml-testing-toolkit Helm chart for Kubernetes
name: ml-testing-toolkit
version: 11.2.0
appVersion: "ml-testing-toolkit: v11.1.1 ml-testing-toolkit-ui: v11.2.0"
home: http://mojaloop.io
icon: http://mojaloop.io/images/logo.png
sources:
  - https://github.com/mojaloop/mojaloop
  - https://github.com/mojaloop/helm
  - https://github.com/mojaloop/ml-testing-toolkit
  - https://github.com/mojaloop/ml-testing-toolkit-ui
  - https://github.com/modusbox/connection-manager-api
  - https://github.com/modusbox/connection-manager-ui
maintainers:
  - name: Georgi Logodazhki
    email: georgi.logodazhki@modusbox.com
  - name: Vijay Kumar
    email: vijaya.guthi@modusbox.com
