# requirements.yaml
dependencies:
- name: ml-testing-toolkit-frontend
  version: 11.2.0
  repository: "file://./chart-frontend"
  condition: global.mlTestingToolkitFrontend.enabled
- name: ml-testing-toolkit-backend
  version: 11.1.1
  repository: "file://./chart-backend"
  condition: global.mlTestingToolkitBackend.enabled
- name: connection-manager-frontend
  version: 1.6.9
  repository: "file://./chart-connection-manager-frontend"
  condition: global.connectionManagerFrontend.enabled
- name: connection-manager-backend
  version: 1.6.5
  repository: "file://./chart-connection-manager-backend"
  condition: global.connectionManagerBackend.enabled
- name: percona-xtradb-cluster
  version: 1.0.4
  repository: https://kubernetes-charts.storage.googleapis.com
  alias: mysql
  condition: global.mysql.enabled
- name: mongodb
  version: 7.8.10
  repository: https://kubernetes-charts.storage.googleapis.com/
  alias: mongodb
  condition: global.mongodb.enabled
- name: keycloak
  version: 9.1.0
  repository: https://codecentric.github.io/helm-charts
  condition: global.keycloak.enabled