# requirements.yaml
dependencies:
- name: ml-testing-toolkit-frontend
  version: 11.2.0
  repository: "file://./chart-frontend"
  condition: ml-testing-toolkit-frontend.enabled
- name: ml-testing-toolkit-backend
  version: 11.2.2
  repository: "file://./chart-backend"
  condition: ml-testing-toolkit-backend.enabled
- name: connection-manager-frontend
  version: 1.6.9
  repository: "file://./chart-connection-manager-frontend"
  condition: connection-manager-frontend.enabled
- name: connection-manager-backend
  version: 1.6.5
  repository: "file://./chart-connection-manager-backend"
  condition: connection-manager-backend.enabled
- name: percona-xtradb-cluster
  version: 1.0.4
  repository: https://kubernetes-charts.storage.googleapis.com
  alias: mysql
  condition: mysql.enabled
- name: mongodb
  version: 7.8.10
  repository: https://kubernetes-charts.storage.googleapis.com/
  alias: mongodb
  condition: mongodb.enabled
- name: keycloak
  version: 9.1.0
  repository: https://codecentric.github.io/helm-charts
  condition: keycloak.enabled
