# This is a YAML-formatted file.
# Declare global configurations
global: {}

ml-testing-toolkit-backend:
  enabled: true
  ## depends on connection-manager-backend, keycloak and mongodb
  ## you could disable them in the values.yaml of the sub chart

ml-testing-toolkit-frontend:
  enabled: true

connection-manager-backend:
  enabled: true
  ## keycloak and mysql
  ## you could disable them in the values.yaml of the sub chart
connection-manager-frontend:
  enabled: true

mysql:
  ## repo and documentation https://github.com/helm/charts/tree/master/stable/percona-xtradb-cluster

  ## disable when connection-manager-backend is disabled
  ## there is a dependency check in connection-manager-backend sub chart so make sure that values are matching
  enabled: true
  image:
    repository: "percona/percona-xtradb-cluster"
    tag: "5.7.19"
    pullPolicy: Always

  nameOverride: mysql

  replicas: 1

  mysqlUser: mcm
  mysqlPassword: mcm
  mysqlDatabase: mcm
  allowRootFrom: "%"

  persistence:
    enabled: false
    accessMode: ReadWriteOnce
    size: 8Gi

  nodeSelector: {}

  podAnnotations: {}

  tolerations: []

  configFiles:
    node.cnf: |+
      [mysqld]
      datadir=/var/lib/mysql
      default_storage_engine=InnoDB
      binlog_format=ROW
      innodb_flush_log_at_trx_commit  = 0
      innodb_flush_method             = O_DIRECT
      innodb_file_per_table           = 1
      innodb_autoinc_lock_mode=2
      bind_address = 0.0.0.0
      wsrep_slave_threads=2
      wsrep_cluster_address=gcomm://
      wsrep_provider=/usr/lib/galera3/libgalera_smm.so
      wsrep_cluster_name=galera
      wsrep_sst_method=xtrabackup-v2
      pxc_strict_mode=DISABLED
      max_connections=999
      max_user_connections=994
      thread_cache_size=999

  metricsExporter:
    enabled: true
    tag: v0.11.0
    commandOverrides: []
    argsOverrides: []

  logTail: true

  service:
    type: ClusterIP
    port: 3306
    externalIPs: []


mongodb:
  ## repo and documentation https://github.com/bitnami/charts/tree/master/bitnami/mysql

  ## there is a dependency check in ml-testing-toolkit-backend sub chart so make sure that values are matching
  enabled: true
  nameOverride: mongodb

  image:
    registry: docker.io
    repository: bitnami/mongodb
    tag: latest
    pullPolicy: Always


  usePassword: true
  mongodbRootPassword: adminpass
  mongodbUsername: ttk
  mongodbPassword: ttk
  mongodbDatabase: ttk

  mongodbEnableIPv6: true

  mongodbExtraFlags: []

  clusterDomain: cluster.local

  service:
    annotations: {}
    type: ClusterIP
    port: 27017

  replicaSet:
    enabled: false
    useHostnames: true
    name: rs0
    replicas:
      secondary: 1
      arbiter: 1
    pdb:
      minAvailable:
        primary: 1
        secondary: 1
        arbiter: 1

  podAnnotations: {}

  podLabels: {}

  resources: {}

  nodeSelector: {}

  affinity: {}

  tolerations: []

  persistence:
    enabled: false
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    annotations: {}

  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1

keycloak:
  ## repo and documentation https://github.com/codecentric/helm-charts/tree/master/charts/keycloak
  ## check the documentation in the repo for additional details

  ## there is a dependency check in ml-testing-toolkit-backend and connection-manager-backend sub charts so make sure that values are matching
  enabled: true
  image:
    repository: quay.io/keycloak/keycloak
    tag: "10.0.2"
  ## -Dkeycloak.profile.feature.upload_scripts=enabled
  extraEnv: |
    - name: KEYCLOAK_USER
      value: admin
    - name: KEYCLOAK_PASSWORD
      value: admin
    - name: KEYCLOAK_IMPORT
      value: /realm/realm.json -Dkeycloak.profile.feature.upload_scripts=enabled
  
  extraVolumes: |
    - name: realm-secret
      secret:
        secretName: realm-secret
  extraVolumeMounts: |
    - name: realm-secret
      mountPath: "/realm/"
      readOnly: true
  service:
    type: ClusterIP
    httpPort: 7080
    rules: 
      - host: testing-toolkit-keycloak.local
        paths: [/]
    tls: []
  ingress:
    enabled: true
    rules:
      - host: testing-toolkit-keycloak.local
        paths: [/]
    tls: []