global:
  # commands are used in 
  mysql:
    command: until printf "." && nc -z -w 2 $mysql_host $mysql_port; do sleep 2; done;
  keycloak:
    command: until printf "." && nc -z -w 2 $keycloak_host $keycloak_port; do sleep 2; done;
replicaCount: 1
enabled: true
image:
  repository: modusbox/connection-manager-api
  version: 1.6.5
  pullPolicy: Always

service:
  type: ClusterIP
  ports:
    adminApi:
      name: admin-api
      externalPort: 5061
      internalPort: 3001

ingress:
  enabled: true
  hosts:
    connection-manager.local:
      port: 5061
      paths: ['/api/']
  tls:
  annotations:

## $snake_case values are dynamic
config:
  DATABASE_HOST: "$mysql_host"
  DATABASE_PORT: "$mysql_port"
  DATABASE_USER: "some_mysql_user"
  DATABASE_PASSWORD: "some_mysql_pasword"
  DATABASE_SCHEMA: "some_mysql_database"
  MYSQL_ROOT_PASSWORD: "some_mysql_root_password"
  PORT: "5061"
  MTA_ROLE: "Application/MTA"
  PTA_ROLE: "Application/PTA"
  EVERYONE_ROLE: "Internal/everyone"
  AUTH_ENABLED: "TRUE"
  P12_PASS_PHRASE: "SOME_S3C4R3_P@SS"
  OAUTH2_ISSUER: "http://$auth_host:$auth_port$auth_issuer_path"
  OAUTH2_TOKEN_ISS: "http://$auth_host:$auth_port$auth_token_iss_path"
  APP_OAUTH_CLIENT_KEY: "some_client_key"
  APP_OAUTH_CLIENT_SECRET: "some_client_secret"
  EMBEDDED_CERTIFICATE: "some_embeded_certificate"