global:
  # commands are used in 
  mysql:
    enabled: true
    command: until printf "." && nc -z -w 2 $mysql_host $mysql_port; do sleep 2; done;
    host: "$release_name-mysql"
    port: "3306"
  keycloak:
    enabled: true
    command: until printf "." && nc -z -w 2 $keycloak_host $keycloak_port; do sleep 2; done;
    host: "$release_name-keycloak-http"
    port: "7080"
    paths:
      issuer: /auth/realms/testingtoolkit/protocol/openid-connect/token
      token_iss: /auth/realms/testingtoolkit
  defaultAuth:
    host: "$release_name-ml-testing-toolkit-backend"
    port: "5050"
    paths:
      issuer: /api/oauth2/token
      token_iss: /api/oauth2/token
replicaCount: 1
enabled: true
image:
  repository: modusbox/connection-manager-api
  version: 1.6.5
  pullPolicy: Always

service:
  type: ClusterIP
  ports:
    adminApi:
      name: admin-api
      externalPort: 5061
      internalPort: 3001

ingress:
  enabled: true
  hosts:
    connection-manager.local:
      port: 5061
      paths: ['/api/']
  tls:
  annotations:

## $snake_case values are dynamic
config:
  DATABASE_HOST: "$mysql_host"
  DATABASE_PORT: "$mysql_port"
  DATABASE_USER: mcm
  DATABASE_PASSWORD: mcm
  DATABASE_SCHEMA: mcm
  MYSQL_ROOT_PASSWORD: modus123
  PORT: "5061"
  MTA_ROLE: "Application/MTA"
  PTA_ROLE: "Application/PTA"
  EVERYONE_ROLE: "Internal/everyone"
  AUTH_ENABLED: "TRUE"
  P12_PASS_PHRASE: "SOME_S3C4R3_P@SS"
  OAUTH2_ISSUER: "http://$auth_host:$auth_port$auth_issuer_path"
  OAUTH2_TOKEN_ISS: "http://$auth_host:$auth_port$auth_token_iss_path"
  APP_OAUTH_CLIENT_KEY: "ttk"
  APP_OAUTH_CLIENT_SECRET: "23b898a5-63d2-4055-bbe1-54efcda37e7d"
  EMBEDDED_CERTIFICATE: |-
    -----BEGIN PUBLIC KEY-----
    MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDda1T6cyWogfG/xlUb3+gWZI0jsnlSGbf3PF89NCgS+n6HUJ0A2Ezmu/n9Gfkm8Rjyst914Vq9ebsueXHIc+Ad76+q3MASF1hRUTfnvH/v6rDguPvI6Jb/M9jGn5b2hglcg3B9Y7Tgv70bcV7oCweP68CPbIrTWjR9gyjmSHfYhwIDAQAB
    -----END PUBLIC KEY-----