{{- $RELEASE_NAME := .Release.Name -}}
{{- $MONGODB := (.Values.global.mongodb) -}}
{{- $CONNECTION_MANAGER := (.Values.global.connectionManagerBackend) -}}
{{- $KEYCLOAK := (.Values.global.keycloak) -}}
{{- $DEFAULT_AUTH := (.Values.global.defaultAuth) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ml-testing-toolkit-backend.fullname" . }}-config-default
  labels:
    app.kubernetes.io/name: {{ include "ml-testing-toolkit-backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
{{- if (index $KEYCLOAK "enabled") }}
  {{- range $k, $v := .Values.config }}
    {{ $k }}: {{ ($v | toPrettyJson | quote | replace "$mongodb_host" (index $MONGODB "host") | replace "$mongodb_port" (index $MONGODB "port") | replace "$auth_host" (index $KEYCLOAK "host")  | replace "$auth_port" (index $KEYCLOAK "port") | replace "$auth_issuer_path" (index $KEYCLOAK "paths" "issuer") | replace "$auth_token_iss_path" (index $KEYCLOAK "paths" "tokenIss") | replace "$auth_embedded_certificate" (index $KEYCLOAK "embeddedCertificate") | replace "$connection_manager_host" (index $CONNECTION_MANAGER "host") | replace "$connection_manager_port" (index $CONNECTION_MANAGER "port") | replace "$release_name" $RELEASE_NAME)  }}
  {{- end }}
{{- else}}
  {{- range $k, $v := .Values.config }}
    {{ $k }}: {{ ($v | toPrettyJson | quote | replace "$mongodb_host" (index $MONGODB "host") | replace "$mongodb_port" (index $MONGODB "port") | replace "$auth_host" (index $DEFAULT_AUTH "host")  | replace "$auth_port" (index $DEFAULT_AUTH "port") | replace "$auth_issuer_path" (index $DEFAULT_AUTH "paths" "issuer") | replace "$auth_token_iss_path" (index $DEFAULT_AUTH "paths" "tokenIss") | replace "$auth_embedded_certificate" (index $DEFAULT_AUTH "embeddedCertificate") | replace "$connection_manager_host" (index $CONNECTION_MANAGER "host") | replace "$connection_manager_port" (index $CONNECTION_MANAGER "port") | replace "$release_name" $RELEASE_NAME)  }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ml-testing-toolkit-backend.fullname" . }}-config-extra-environments
  labels:
    app.kubernetes.io/name: {{ include "ml-testing-toolkit-backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  {{- range $k, $v := .Values.extraEnvironments }}
    {{ $k }}: {{ ($v | toPrettyJson | quote | replace "$release_name" $RELEASE_NAME)  }}
  {{- end }}
